export const colors = {
  primary: '#2554EE',
  primarySoft: '#DCE7FF',
  navyHeaderStart: '#0B1B3A',
  navyHeaderEnd: '#132A5C',
  success: '#1F9D55',
  successBg: '#DFF5E6',
  danger: '#E23D3D',
  dangerBg: '#FDE7E7',
  investment: '#7C4DE0',
  investmentBg: '#EFE7FB',
  transfer: '#2554EE',
  transferBg: '#E3ECFF',
  warning: '#E68A2E',
  warningBg: '#FCEFD9',
  surface: '#FFFFFF',
  background: '#F3F6FC',
  border: '#E7ECF5',
  text: '#101828',
  textMuted: '#667085',
} as const;

export type ColorToken = keyof typeof colors;

export const cssColorVariables = {
  '--primary': colors.primary,
  '--primary-soft': colors.primarySoft,
  '--navy-header-start': colors.navyHeaderStart,
  '--navy-header-end': colors.navyHeaderEnd,
  '--success': colors.success,
  '--success-bg': colors.successBg,
  '--danger': colors.danger,
  '--danger-bg': colors.dangerBg,
  '--investment': colors.investment,
  '--investment-bg': colors.investmentBg,
  '--transfer': colors.transfer,
  '--transfer-bg': colors.transferBg,
  '--warning': colors.warning,
  '--warning-bg': colors.warningBg,
  '--surface': colors.surface,
  '--background': colors.background,
  '--border': colors.border,
  '--text': colors.text,
  '--text-muted': colors.textMuted,
} as const;
